name: CI

on:
  push:
    branches: [ main, v2 ]
  pull_request:
    branches: [ main, v2 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: set api key
        env:
          APP_INSIGHTS_KEY: ${{ secrets.AZURE_APP_INSIGHTS_API_KEY }}
        run: echo "export const appinsights_key = \"$APP_INSIGHTS_KEY\";" > src-packed/secrets.js

      - name: npm install
        run: npm install

      - name: build extension
        run: npx xt-build

      - name: run tests
        run: npx xt-test

      # Upload unzipped artifact content to avoid creating a nested .zip artifact
      - name: unzip release.zip
        run: unzip release.zip -d unzipped-release

      - name: archive release.zip
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: unzipped-release
          if-no-files-found: error
